"""empty message

Revision ID: a6214a0487e5
Revises: e34c781cde58
Create Date: 2024-04-10 12:08:08.394220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6214a0487e5'
down_revision = 'e34c781cde58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_time_pst', sa.DateTime(), nullable=True))
        batch_op.drop_column('order_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('order_time_pst')

    # ### end Alembic commands ###
