"""empty message

Revision ID: e34c781cde58
Revises: 
Create Date: 2024-04-10 10:51:42.955651

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e34c781cde58"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("district_name", sa.String(length=128), nullable=False),
        sa.Column("city_name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("unique_order_number", sa.String(length=128), nullable=False),
        sa.Column("order_time_pst", sa.DateTime(), nullable=True),
        sa.Column("district_city_id", sa.Integer(), nullable=False),
        sa.Column("rptg_amt", sa.Float(), nullable=False),
        sa.Column("currency_cd", sa.String(length=10), nullable=False),
        sa.Column("order_qty", sa.Integer(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_city_id"],
            ["cities.id"],
        ),
        sa.PrimaryKeyConstraint("unique_order_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("cities")
    # ### end Alembic commands ###
